// @ts-nocheck
// eslint-disable
/**
 * ---------------------------------------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------------------------------------
 * */

import {
  useLocalePath as _useLocalePath,
  useLocaleRoute as _useLocaleRoute
} from 'vue-i18n-routing';
import type {
  TypedRouteLocationRawFromName,
  TypedRouteFromName,
  TypedLocationAsRelativeRaw
} from './__router';
import type { RoutesNamesList } from './__routes';

export type I18nLocales = '[object Object]' | '[object Object]';

export type TypedToLocalePath = <T extends RoutesNamesList = never>(
  to: TypedRouteLocationRawFromName<T>,
  locale?: I18nLocales | undefined
) => [T] extends [never] ? string : Required<TypedLocationAsRelativeRaw<T>>;

export function useLocalePath(
  options?: Pick<NonNullable<Parameters<typeof _useLocalePath>[0]>, 'i18n'>
): TypedToLocalePath {
  return _useLocalePath(options) as any;
}

export type TypedLocaleRoute = <T extends RoutesNamesList>(
  to: TypedRouteLocationRawFromName<T>,
  locale?: I18nLocales | undefined
) => TypedRouteFromName<T>;

export function useLocaleRoute(
  options?: Pick<NonNullable<Parameters<typeof _useLocaleRoute>[0]>, 'i18n'>
): TypedLocaleRoute {
  return _useLocaleRoute(options) as any;
}
